[window]
# Transparencia espiritual (ajusta de 0.0 a 1.0)
opacity = 0.96
blur = true # Esto funciona de maravilla con tu Picom

[window.padding]
# Un poco de aire para que el texto no toque los bordes redondeados
x = 15
y = 15

[font]
normal = { family = "Ubuntu Mono", style = "Regular" } #SauceCodePro Nerd Font
bold = { family = "Ubuntu Mono", style = "Bold" }
italic = { family = "Ubuntu Mono", style = "Italic" }
size = 14.0
offset.x = 1
offset.y = 0

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[general]
import = [
    "~/.config/alacritty/canolitos.toml"
    #"~/.config/alacritty/catppuccin-mocha.toml",
    #"~/.config/alacritty/tokyo-night-storm.toml",
    #"~/.config/alacritty/dracula.toml",
]
